server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net
    manager:
        name: TinyDB
        connection: /tmp/pygeoapi-process-manager.db
        output_dir: /tmp/

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Diving into pygeoapi default instance
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://dive.pygeoapi.io
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi Development Team
        url: https://pygeoapi.io
    contact:
        name: pygeoapi Development Team
        position: pygeoapi Development Team
        address: 9450 SW Gemini Dr. #42523
        city: Beaverton
        stateorprovince: Oregon
        postalcode: 97008
        country: United States of America
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: pygeoapi@gmail.com
        url: https://pygeoapi.io
        hours: 24/7
        instructions: During hours of service.
        role: pointOfContact

resources:
    # obs:
    #     type: collection
    #     title: Observations
    #     description: My cool observations
    #     keywords:
    #         - observations
    #         - monitoring
    #     linked-data:
    #         context:
    #             - datetime: https://schema.org/DateTime
    #             - vocab: https://example.com/vocab#
    #               stn_id: "vocab:stn_id"
    #               value: "vocab:value"
    #     links:
    #         - type: text/csv
    #           rel: canonical
    #           title: data
    #           href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
    #           hreflang: en-US
    #         - type: text/csv
    #           rel: alternate
    #           title: data
    #           href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
    #           hreflang: en-US
    #     extents:
    #         spatial:
    #             bbox: [-180,-90,180,90]
    #             crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #         temporal:
    #             begin: 2000-10-30T18:24:39Z
    #             end: 2007-10-30T08:57:29Z
    #     providers:
    #         - type: feature
    #           name: CSV
    #           data: tests/data/obs.csv
    #           id_field: id
    #           geometry:
    #               x_field: long
    #               y_field: lat

    # lakes:
    #     type: collection
    #     title: Large Lakes
    #     description: lakes of the world, public domain
    #     keywords:
    #         - lakes
    #     links:
    #         - type: text/html
    #           rel: canonical
    #           title: information
    #           href: https://www.naturalearthdata.com/
    #           hreflang: en-US
    #     extents:
    #         spatial:
    #             bbox: [-180,-90,180,90]
    #             crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #         temporal:
    #             begin: 2011-11-11
    #             end: null  # or empty
    #             trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
    #     providers:
    #         - type: feature
    #           name: GeoJSON
    #           data: tests/data/ne_110m_lakes.geojson
    #           crs:
    #             - http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #             - http://www.opengis.net/def/crs/EPSG/0/3857
    #           storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #           id_field: id

    hyderabad:
        type: collection
        title: Greater Hyderabad Municipal Corporation ward boundaries
        description: The city ward boundaries represent the administrative and electoral boundary areas of the city. It plays a great role in planning of the city, for each council of the municipal corporation.
        keywords:
          - Boundaries
          - Administrative
          - Ward
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://livingatlas-dcdev.opendata.arcgis.com/datasets/a090c89d52f1498f96a82e97b8bfb83e_0/
              hreflang: en-US
        extents:
            spatial:
                bbox: [78.2379194985166180,17.2908061510471995,78.6217049083810764,17.5618443356918768]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
        providers:
            - crs:
            - http://www.opengis.net/def/crs/OGC/1.3/CRS84
            - http://www.opengis.net/def/crs/EPSG/0/4326
            - type: feature
              storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              name: GeoJSON
              data: /data/greater_hyderabad_municipal_corporation_ward_Boundaries.geojson
              id_field: id
